#!/bin/bash

hash=$1
cracked=0
not_installed=0

check(){
	which $1 >/dev/null 2>/dev/null
	if [ $? -eq 0 ]
	then
		echo -n ""
	else
		echo $1 is not installed.
		not_installed=1
	fi
}

check hashcat

touch /tmp/err

if [ $not_installed -eq 1 ]
then
	echo "Install the required tool(s)"
	exit
fi

touch /tmp/crack

x=$(hashcat $hash 2>/dev/null | grep "of your input" | cut -d " " -f 8)
hashcat $hash 2>/dev/null | grep "of your input" -A $((x+3)) | tail -n $x 2>/dev/null | awk '{$1=$1};1' >/tmp/possible-hashtypes

echo -e "\033[1;32m[+] Finding Possible Hash Types\033[0m"

cat /tmp/possible-hashtypes | cut -d "|" -f 2 | while read line
do
	echo -e "    \033[1;35m$line\033[0m"
done
echo ""

if [ -f "/usr/share/wordlists/rockyou.txt" ]; then
	cat /tmp/possible-hashtypes | while read line
	do

		hashname=$(echo $line | cut -d "|" -f 2 | awk '{$1=$1};1')
		hashval=$(echo $line | cut -d "|" -f 1 | awk '{$1=$1};1')

		echo -e "Trying \033[1;35m$(echo $line | cut -d "|" -f 2 | awk '{$1=$1};1')\033[0m"
		if [ $# -eq 2 ]
		then
			hashcat -m $hashval -a 0 -d 1 $hash $2 > /tmp/crack
		else
			hashcat -m $hashval -a 0 -d 1 $hash /usr/share/wordlists/rockyou.txt 2>/tmp/err >/tmp/crack
		fi

		if [ $? -eq 0  ]
		then
			cat /tmp/crack | grep Cracked >/dev/null
			if [ $? -eq 0 ]
			then
				cat /tmp/crack | grep Cracked -B 3 | head -n 1 | cut -d ":" -f 2 | xargs -I{} bash -c "echo -e '\033[1;32mThe Plaintext Is : \033[0m\033[7;34m{}\033[0m'"
				cracked=1
			else
				echo -e '\033[1;32m[+] Found The Hash in Potfile\033[0m'
				cat "/home/$(whoami)/.local/share/hashcat/hashcat.potfile" | grep -i $hash | cut -d ":" -f 2 | xargs -I{} bash -c "echo -e '\033[1;32mThe Plaintext Is : \033[0m\033[7;34m{}\033[0m'"
				cracked=1
			fi
			exit
		fi

		if [ $cracked -eq 0 ]
		then
			echo -e "\033[1;31mPassword Not Found In Wordlist\033[0m"
		fi
	done
	rm /tmp/crack /tmp/err /tmp/possible-hashtypes
else
	echo "The file rockyou.txt does not exist. Edit the code if you want to select another word-list."
	exit
fi
